kitakami-common: "LOCAL_ENFORCE_USES_LIBRARIES := false" inserted for some apps.
This prevents error messages like this:

error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: [android.hidl.manager@1.0-java]
	- optional libraries in build system: []
	                 vs. in the manifest: []
	- tags in the manifest (vendor/sony/kitakami-common/proprietary/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk):
		uses-library:'android.hidl.manager@1.0-java'

Change-Id: I22c1d7a85587b95d46958b2e0c1db6e397d2bdd6